---
  - hosts: resume
    tasks:
      - name: Install requirements with apt
        apt: name={{ item }} update_cache=yes state=latest
        with_items:
          - git
          - apt-transport-https
          - ca-certificates
        become: true
      - name: Add gpg key
        shell: apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
        become: true
      - name: Add docker repo
        shell: echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
        become: true
      - name: Install docker-engine
        apt: name=docker-engine update_cache=yes state=latest
        become: true
      - name: Start docker
        shell: service docker start
        become: true
      - name: Set docker to start on boot
        shell: systemctl enable docker
        become: true
